### ISSUE TITLE
Invoice should display the tearoff at the same point on the page

### ISSUE THREAD

**Issue by RichardWigley** [BCS-io/letting#252]
Currently an invoice tearoff is affected by the number of charges (products) - we want it to occur at the same place regardless of the number of charges (if one or 5)

**Comment by MargaretLangley** [comment]
There are a number of items on the invoice page which can push the tear off label down the page:

1. The products, list of charges - this  has been fixed
2. The two comment lines - blank lines are put out if there is no comment
3. The billing address  can vary normally between 4 to 7 lines. Because this is within invoice_decorator not sure how to fix this

**Comment by RichardWigley** [comment]
Fix for 3, the blling address can vary between 4 and 7 lines ...   276e76889e4d4d4cfa43f7a188b5e0772c43cd80
