### ISSUE TITLE
The account form to have next/previous record to speed up editing. 

### ISSUE THREAD

**Issue by MargaretLangley** [BCS-io/letting#265]
The account form - property/edit  to have next/previous record to speed up editing
Account page when updated needs check that data has been updated and user is not merrily going on filling in the form but not saving it

**Comment by RichardWigley** [comment]
Adding next/previous that works in the same way as on a show/view requires that we do not leave the form and loose edited but unsaved data.

Approach 1 - use JS to prevent leaving a form with edited data.
Approach 2 - save the data and then go onto the next / previous record.

***

Approach 1

 [ nothing to report ]

Approach 2 - save the data and then go onto the next / previous record.

1. Basic submit button 
````html
<input type="submit" name='next'>
````
1. 1. Pro: 
  -  It just works - clicking on it causes a submit.
  -  it sets the params['next']
1. 2. Con:
  -  does not support HTML inside of it, since it's a single self-closing tag.


2. Button 

````html
<button class='btn btn-primary'>
  <%= fa_icon("search") %>
</button>
````

2. 1. Pro:
  -  It is a tag pair so html elements can be set inside it.
2. 2. Con:
  -
